### ISSUE TITLE
Separated line painted in bad place (due to anonymous)

### ISSUE THREAD

**Issue by jaclas** [cnpack/cnwizards#47] opened 2017-01-26 09:25 UTC
![ashampoo_snap_2017 01 26_10h20m16s_001_](https://cloud.githubusercontent.com/assets/17312717/22326055/7802af94-e3b1-11e6-9262-b210bc074f21.png)

**Comment by shanzhashu** [comment] 2017-02-10 01:28
Could you download our latest nightly-build version 877 to try it again? This feature was in refactoring before so maybe has some side effects.

http://www.cnpack.org/downbuilds.php

**Comment by jaclas** [comment] 2017-02-13 10:42
Problem still exist:
![ashampoo_snap_2017 02 13_11h41m47s_001_](https://cloud.githubusercontent.com/assets/17312717/22880179/83223e7e-f1e1-11e6-9942-3da82a7d229a.png)

**Comment by shanzhashu** [comment] 2017-02-20 02:56
Thanks for the snapshot, could you tell the IDE version of Delphi?

**Comment by jaclas** [comment] 2017-02-20 21:10
Berlin Update 1

**Comment by shanzhashu** [comment] 2017-02-21 07:39
So weird that I can't reproduce the problem according to the code piece in snapshot. Could you send the whole file to me to let me test it? master@cnpack.org

If can't send the file to me by privacy reason, you can also remove "Sensitive" part in this file and only keep the "stub" to reproduce this problem. 

Thanks.

**Comment by jaclas** [comment] 2017-02-21 08:31
This code enough:
```
unit Unit2;

interface

implementation

function TCuculusEngine.AddProduct(const aProductId : Integer; aProductName : string): Integer;
begin
  lExist := fProductList.TryGetFirst(lProduct, function(const aProduct: RProductData): Boolean
                                 begin
                                   Result := SameText(aProductName, aProduct.ProductName);
                                 end);
  if lExist then
  begin

  end
  else
  begin
    lExist := fProductList.TryGetFirst(lProduct, function(const aProduct: RProductData): Boolean
                                 begin
                                   Result := aProductId = aProduct.ProductId;
                                 end);
  end;
end.
```

And leave empty line after "if lExist then begin":

![ankieta_02](https://cloud.githubusercontent.com/assets/17312717/23156731/7476e900-f818-11e6-894c-cda96c758733.png)

**Comment by shanzhashu** [comment] 2017-02-21 08:52
Thanks. I'll check it again.

**Comment by shanzhashu** [comment] 2017-02-22 05:33
Got it. It's a bug caused by our source parsing refactoring and now fixed.

Could you please download our latest nighly-build 881 to try it again?

http://www.cnpack.org/downbuilds.php

**Comment by jaclas** [comment] 2017-02-22 08:15
Now is ok :-) Thanks

**Closed** 2017-02-28 09:43 UTC
